version: '2'
services:
    letall-app:
        image: letall
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://letall-mysql:3306/letall?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=letall-elasticsearch:9300
        ports:
            - 8080:8080
    letall-mysql:
        extends:
            file: mysql.yml
            service: letall-mysql
    letall-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: letall-elasticsearch
